sudo: false
language: java
jdk:
  - oraclejdk8
install: 
  - wget --quiet --output-document=/tmp/ceylon.zip $CEYLON
  - unzip /tmp/ceylon.zip
  - export PATH=$PATH:$PWD/ceylon-$CEYLON_VERSION/bin/
before_script: 
  - ceylon compile
script: 
  - ceylon test $TEST_MODULE
env:
  global:
    - CEYLON_VERSION=1.3.2
    - CEYLON="http://ceylon-lang.org/download/dist/1_3_2"
    - TEST_MODULE="test.com.athaydes.specks"
